version: '3'

services:
  db:
    image: postgres:16
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      PPOSTGRES_USER: postgres
      POSTGRES_DB: appdata
      POSTGRES_PASSWORD: apppassword
volumes:
  db-store: